# Application configuration
app:
  name: "GatoImidj"
  description: "stuff about cats"

# Environment configuration
environment:
  development:
    debug: true
    cors_origins:
      - http://localhost
      - http://localhost:8000
  testing:
    debug: true
    cors_origins:
      - http://localhost
      - http://localhost:8000
  production:
    debug: false
    cors_origins:
      - https://example.com